-- CreateTable
CREATE TABLE "public"."solicitudes_compra" (
    "id" INTEGER NOT NULL,
    "hora_de_inicio" TIMESTAMP(3),
    "hora_de_finalizacion" TIMESTAMP(3),
    "correo_electronico" TEXT NOT NULL,
    "nombre" TEXT NOT NULL,
    "planta" TEXT,
    "departamento" TEXT,
    "tipo_de_compra" TEXT,
    "concepto_de_gasto" TEXT,
    "tipo_de_rc" TEXT,
    "adjuntar_cotizaciones" TEXT,
    "cantidad_1" TEXT,
    "unidad_de_medida_1" TEXT,
    "descripcion_del_articulo_1" TEXT,
    "uso_1" TEXT,
    "precio_unitario_1" TEXT,
    "proveedor_opcion_1_1" TEXT,
    "proveedor_opcion_2_1" TEXT,
    "proveedor_opcion_3_1" TEXT,
    "quieres_agregar_otro_articulo_1" TEXT,
    "cantidad_2" TEXT,
    "unidad_de_medida_2" TEXT,
    "descripcion_del_articulo_2" TEXT,
    "uso_2" TEXT,
    "precio_unitario_2" TEXT,
    "proveedor_opcion_1_2" TEXT,
    "proveedor_opcion_2_2" TEXT,
    "proveedor_opcion_3_2" TEXT,
    "quieres_agregar_otro_articulo_2" TEXT,
    "cantidad_3" TEXT,
    "unidad_de_medida_3" TEXT,
    "descripcion_del_articulo_3" TEXT,
    "uso_3" TEXT,
    "precio_unitario_3" TEXT,
    "proveedor_opcion_1_3" TEXT,
    "proveedor_opcion_2_3" TEXT,
    "proveedor_opcion_3_3" TEXT,
    "quieres_agregar_otro_articulo_3" TEXT,
    "cantidad_4" TEXT,
    "unidad_de_medida_4" TEXT,
    "descripcion_del_articulo_4" TEXT,
    "uso_4" TEXT,
    "precio_unitario_4" TEXT,
    "proveedor_opcion_1_4" TEXT,
    "proveedor_opcion_2_4" TEXT,
    "proveedor_opcion_3_4" TEXT,
    "quieres_agregar_otro_articulo_4" TEXT,
    "cantidad_5" TEXT,
    "unidad_de_medida_5" TEXT,
    "descripcion_del_articulo_5" TEXT,
    "uso_5" TEXT,
    "precio_unitario_5" TEXT,
    "proveedor_opcion_1_5" TEXT,
    "proveedor_opcion_2_5" TEXT,
    "proveedor_opcion_3_5" TEXT,
    "costo_total_de_la_compra" TEXT,
    "comentarios" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "solicitudes_compra_pkey" PRIMARY KEY ("id")
);
